<?php

// ยี่ห้อรถที่จดทะเบียนในไทย — อ้างอิงอันดับยอดจดทะเบียนของกรมการขนส่งทางบก (car250, ก.ค. 2569)
// ใช้ทั้งในฟอร์มจองที่จอดและในคำสั่งที่ส่งให้ Claude Vision (ดู CarScanService::detect())
// เพื่อให้ยี่ห้อที่ผู้ใช้เลือกกับที่ AI อ่านได้ เทียบกันแบบ exact match ได้ตรงกัน — แนวเดียวกับ car_colors.php
//
// "อื่น ๆ" มีไว้ให้รถที่ยี่ห้อไม่อยู่ในรายการยังจองได้ (ระบบยังจับคู่ด้วยสีได้ตามกติกา ยี่ห้อ "หรือ" สี)
return [
    'Aston Martin',
    'Audi',
    'Avatr',
    'BMW',
    'BYD',
    'Bentley',
    'Changan',
    'Chery',
    'Chevrolet',
    'Daihatsu',
    'Deepal',
    'Denza',
    'Ferrari',
    'Ford',
    'Foton',
    'GAC Aion',
    'GWM',
    'Geely',
    'Haval',
    'Hino',
    'Honda',
    'Hyundai',
    'Isuzu',
    'Jaecoo',
    'Jaguar',
    'Jeep',
    'KIA',
    'Lamborghini',
    'Land Rover',
    'Leapmotor',
    'Lexus',
    'Lotus',
    'MG',
    'Maserati',
    'Maxus',
    'Mazda',
    'Mercedes-Benz',
    'Mini',
    'Mitsubishi',
    'NIO',
    'Neta',
    'Nissan',
    'Omoda',
    'Peugeot',
    'Porsche',
    'Riddara',
    'Rolls-Royce',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'Volkswagen',
    'Volvo',
    'Wuling',
    'XPeng',
    'Zeekr',
    'อื่น ๆ',
];
